### PR TITLE
Use recommended common names for loggregator certs

### PR DESCRIPTION
**Pull request by mcwumbly**
Follow up to https://github.com/rosenhouse/cf-filler/pull/2

### CODE REVIEW

**Comment by rosenhouse** [comment]
yeah.

but as long as we're looking at this, shouldn't `loggregator_tls_doppler_cert` be the same as `doppler_tls_server_cert`?  

Their [own scripts](https://github.com/cloudfoundry/loggregator/blob/develop/scripts/generate-loggregator-certs) only generate 3 cert/key pairs, not 4.  I think [this commit](https://github.com/cloudfoundry/cf-deployment/commit/008939007842940a271badd966081812a19a513c) is got it wrong.

**Comment by mcwumbly** [comment]
you're right about that commit, see: https://github.com/cloudfoundry/cf-deployment/pull/21

but I think the other certs are still used... haven't looked too closely, but I am guessing doppler acts as a server and a client, and uses different certs depending on the context.

**Comment by mcwumbly** [comment]
Oh hmm... yeah... looking at that commit, I think you may be right, too

**Comment by rosenhouse** [comment]
and the fact that rel-int's own pipeline didn't catch this shows that cf-filler, or something like it, really should be part of the cf-deployment CI.  

a human used magic knowledge to assign the exact same values to two different vars.  they knew those vars needed to be equal.  but the rest of us don't.  

the relationships between the vars needs to be documented / covered by tests.

**Comment by mcwumbly** [comment]
I'm hopeful that [this story](https://www.pivotaltracker.com/story/show/133354789) will help out a lot.

**Pull request merged**
